# Habilita o Console do H2
spring.h2.console.enabled=true

# Define um caminho fácil e um nome fixo para o banco
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:investdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
server.port=8081